<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DviAssetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $assets = [
            ['dvi_interest_id' => 1, 'dvi_question_id' => 3],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 6],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 8],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 11],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 14],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 15],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 24],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 26],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 71],
            ['dvi_interest_id' => 1, 'dvi_question_id' => 87],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 6],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 7],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 14],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 16],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 24],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 26],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 46],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 50],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 90],
            ['dvi_interest_id' => 2, 'dvi_question_id' => 95],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 3],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 12],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 13],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 30],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 38],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 48],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 51],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 76],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 93],
            ['dvi_interest_id' => 3, 'dvi_question_id' => 108],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 12],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 13],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 16],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 17],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 28],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 35],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 56],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 66],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 91],
            ['dvi_interest_id' => 4, 'dvi_question_id' => 101],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 1],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 10],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 13],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 16],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 28],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 36],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 42],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 53],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 64],
            ['dvi_interest_id' => 5, 'dvi_question_id' => 72],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 1],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 3],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 4],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 6],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 8],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 9],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 11],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 22],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 27],
            ['dvi_interest_id' => 6, 'dvi_question_id' => 45],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 1],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 4],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 5],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 8],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 9],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 10],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 15],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 27],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 31],
            ['dvi_interest_id' => 7, 'dvi_question_id' => 97],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 1],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 3],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 4],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 5],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 15],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 30],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 31],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 38],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 57],
            ['dvi_interest_id' => 8, 'dvi_question_id' => 62],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 7],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 12],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 20],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 25],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 37],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 39],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 49],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 60],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 68],
            ['dvi_interest_id' => 9, 'dvi_question_id' => 106],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 1],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 4],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 8],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 9],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 10],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 22],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 59],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 74],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 85],
            ['dvi_interest_id' => 10, 'dvi_question_id' => 109],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 1],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 5],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 6],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 11],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 14],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 18],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 21],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 33],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 36],
            ['dvi_interest_id' => 11, 'dvi_question_id' => 52],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 5],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 9],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 18],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 21],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 25],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 33],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 35],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 37],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 39],
            ['dvi_interest_id' => 12, 'dvi_question_id' => 84],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 18],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 44],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 55],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 61],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 69],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 77],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 79],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 89],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 100],
            ['dvi_interest_id' => 13, 'dvi_question_id' => 104],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 2],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 47],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 65],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 73],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 80],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 88],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 92],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 98],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 102],
            ['dvi_interest_id' => 14, 'dvi_question_id' => 110],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 2],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 19],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 23],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 29],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 34],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 40],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 63],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 67],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 99],
            ['dvi_interest_id' => 15, 'dvi_question_id' => 105],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 2],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 19],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 23],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 29],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 32],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 34],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 40],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 43],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 82],
            ['dvi_interest_id' => 16, 'dvi_question_id' => 94],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 2],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 7],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 17],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 41],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 54],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 70],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 75],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 81],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 96],
            ['dvi_interest_id' => 17, 'dvi_question_id' => 107],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 2],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 7],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 17],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 20],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 32],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 58],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 78],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 83],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 86],
            ['dvi_interest_id' => 18, 'dvi_question_id' => 103],
        ];

        foreach ($assets as $asset) {
            DB::table('dvi_assets')->insert([
                'dvi_interest_id' => $asset['dvi_interest_id'],
                'dvi_question_id' => $asset['dvi_question_id'],
            ]);
        }
    }
}
