<?php

namespace Database\Seeders;

use App\Models\Dvi;
use Illuminate\Database\Seeder;

class DviQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            ['question' => 'Honestly, I am a fairly effective and practical organizer (for example, to organize sports meetings, excursions, sections of an association, etc.)', 'value' => '0.125'],
            ['question' => 'I have a living imagination and I often feel the artistic inspiration.', 'value' => '0.166'],
            ['question' => 'I like laboratory work.', 'value' => '0.200'],
            ['question' => 'I have physical resistance and I like hard work (sports, marches, exercise, etc.)', 'value' => '0.166'],
            ['question' => 'I think the economic aspect is very important in life and should be taken into account.', 'value' => '0.333'],
            ['question' => 'I like to solve things by my own methods.', 'value' => '0.333'],
            ['question' => 'Literature.', 'value' => '0.500'],
            ['question' => 'Physics and chemistry.', 'value' => '0.250'],
            ['question' => 'Mathematical Calculations (operations, problems, etc.)', 'value' => '0.333'],
            ['question' => 'I easily impose myself on my classmates (with my word, my action, etc.)', 'value' => '0.250'],
            ['question' => 'Theoretical mathematics (theorems, deduction of formulas, etc.)', 'value' => '0.333'],
            ['question' => 'I am really interested in solving other people’s problems; I am helpful.', 'value' => '0.500'],
            ['question' => 'Psychology.', 'value' => '0.500'],
            ['question' => 'I work hard to solve a difficult issue or problem.', 'value' => '0.333'],
            ['question' => 'Natural Sciences.', 'value' => '0.333'],
            ['question' => 'History.', 'value' => '0.010'],
            ['question' => 'I easily understand and approve the moods of others. I like to put myself in the place of others.', 'value' => '0.010'],
            ['question' => 'Accounting', 'value' => '0.010'],
            ['question' => 'Sol-fa.', 'value' => '0.010'],
            ['question' => 'I have a remarkable ease of speech and I like to talk.', 'value' => '0.010'],
            ['question' => 'Economics Studies', 'value' => '0.010'],
            ['question' => 'I like to boss groups of people and respond to my orders before another superior (field leader, chief of section, etc.)', 'value' => '0.010'],
            ['question' => 'When I hear some orfeon or choir, and I notice some failure (someone who is tinkering, bad voice, etc.), it bothers me extraordinarily. I am quite sensitive in this.', 'value' => '0.010'],
            ['question' => 'I like to study theoretical problems (scientific, philosophical hypotheses, etc.)', 'value' => '0.010'],
            ['question' => 'I easily get friendships, even if they aren\'t always many.', 'value' => '0.010'],
            ['question' => 'I prefer to study alone (not in company), and I concentrate a lot.', 'value' => '0.010'],
            ['question' => 'I am very interested in the operation of machines and engines and the new mechanical inventions.', 'value' => '0.010'],
            ['question' => 'I am very indignant about the injustices that others sometimes suffer. More than once I have defended others.', 'value' => '0.010'],
            ['question' => 'In the cinema, the musical theme of the film remains in my mind a lot. I remember it even after a long time.', 'value' => '0.010'],
            ['question' => 'I have facility to remember technical or scientific names.', 'value' => '0.010'],
            ['question' => 'I prefer a free and healthy life in the countryside.', 'value' => '0.010'],
            ['question' => 'I like acting in public.', 'value' => '0.010'],
            ['question' => 'I have enough "commercial view" (to find and exploit a source of income, subsidies, profits, etc.) and not rarely I have proven that I am right.', 'value' => '0.010'],
            ['question' => 'Studies of harmony and musical composition.', 'value' => '0.010'],
            ['question' => 'I easily convince others friendly.', 'value' => '0.010'],
            ['question' => 'I like to meditate on social reality.', 'value' => '0.010'],
            ['question' => 'I like travel and hotel life.', 'value' => '0.010'],
            ['question' => 'Anatomy.', 'value' => '0.010'],
            ['question' => 'I enjoy dealing with people and I enjoy the variety of people.', 'value' => '0.010'],
            ['question' => 'I have a good ear for music. I learn songs and melodies soon and well.', 'value' => '0.010'],
            ['question' => 'I have written some poems that liked to knowledgeable people.', 'value' => '0.010'],
            ['question' => 'I would like to help to solve the anguish of the poor in an organized and efficient way (although this requires me a considerable time and effort).', 'value' => '0.010'],
            ['question' => 'Mark the answer positively if either of these two hypotheses is true: I have a good voice for singing, or else; I know how to play an orchestra instrument well.', 'value' => '0.010'],
            ['question' => 'I prefer calm and sedentary work.', 'value' => '0.010'],
            ['question' => 'I like to make repairs and practical arrangements (electrical installation, compose mechanisms, etc.)', 'value' => '0.010'],
            ['question' => 'Philosophy.', 'value' => '0.010'],
            ['question' => 'I like to make sketches, drawings, and cartoons. Others recognize that I have enough skill with them.', 'value' => '0.010'],
            ['question' => 'I have the facility to comfort other people; I am comprehensive and I feel the problems of others in me.', 'value' => '0.010'],
            ['question' => 'I have a lot of ease for languages.', 'value' => '0.010'],
            ['question' => 'I am very interested in the deep study of historical crises.', 'value' => '0.010'],
            ['question' => 'I don\'t mind interrupting sleep several times at night to take care of a sick person.', 'value' => '0.010'],
            ['question' => 'I usually make broad and very realistic plans for the future.', 'value' => '0.010'],
            ['question' => 'I like to intervene in controversial speeches, controversies or public discussions.', 'value' => '0.010'],
            ['question' => 'I have facility to invent interesting histories or stories.', 'value' => '0.010'],
            ['question' => 'I like to collaborate on the orders of a boss.', 'value' => '0.010'],
            ['question' => 'Religion studies.', 'value' => '0.010'],
            ['question' => 'On vacation, or on occasion of visits to the countryside, I am interested in problems and exploitation of farms (birds, rabbits, etc.)', 'value' => '0.010'],
            ['question' => 'I have the skills to declamation, and I have ever acted successfully.', 'value' => '0.010'],
            ['question' => 'Physical Education (gymnastics).', 'value' => '0.010'],
            ['question' => 'French and Italian studies.', 'value' => '0.010'],
            ['question' => 'I prefer the same type of work every day.', 'value' => '0.010'],
            ['question' => 'I am very interested in animals (different breeds of dogs, horses).', 'value' => '0.010'],
            ['question' => 'In moments of inspiration, I can think of original musical themes.', 'value' => '0.010'],
            ['question' => 'Geography.', 'value' => '0.010'],
            ['question' => 'History of art.', 'value' => '0.010'],
            ['question' => 'I am very interested in my classmates when they go through a crisis. Frequently friends ask me for advice.', 'value' => '0.010'],
            ['question' => 'Estudio de Estética Musical.', 'value' => '0.010'],
            ['question' => 'Study English or German.', 'value' => '0.010'],
            ['question' => 'I am neat and tidy in my things, including the presentation of my works.', 'value' => '0.010'],
            ['question' => 'I really enjoy reading poetry.', 'value' => '0.010'],
            ['question' => 'Classmates frequently ask me for clarifications about theorems or mathematical problems.', 'value' => '0.010'],
            ['question' => 'I follow with interest in newspapers and magazines, political and international news.', 'value' => '0.010'],
            ['question' => 'I am very disturbed by the lack of aesthetic taste (decorations, typography, presentation of a publication, etc.)', 'value' => '0.010'],
            ['question' => 'In general, I like competition, fighting. I think many times, gentle and conciliatory procedures achieve nothing.', 'value' => '0.010'],
            ['question' => 'Studies on poetry (rhythm, images, etc.)', 'value' => '0.010'],
            ['question' => 'Before a sick person or animal, I am very curious to know their ailment.', 'value' => '0.010'],
            ['question' => 'I like to work with a fixed schedule.', 'value' => '0.010'],
            ['question' => 'If there is the opportunity, I act with pleasure in comedies, dramas, etc. They say I do it well.', 'value' => '0.010'],
            ['question' => 'I prefer a defined job in which everything is well planned, rather than having to constantly invent solutions to new problems on my own.', 'value' => '0.010'],
            ['question' => 'I like to contemplate panoramas, landscapes, sunsets, the colors of the clouds and the sea, etc.', 'value' => '0.010'],
            ['question' => 'I like to write short articles, reports, etc.', 'value' => '0.010'],
            ['question' => 'Studies on musical performance (instrument).', 'value' => '0.010'],
            ['question' => 'Declamation Studies.', 'value' => '0.010'],
            ['question' => 'I like to organize or cooperate in the sale of something.', 'value' => '0.010'],
            ['question' => 'I like to “tidy up” or help with it (rowdy groups, etc.) and on such occasions, it is necessary to act with effective and rapid sanctions.', 'value' => '0.010'],
            ['question' => 'Literary things are easily recorded in my memory (poetry, speeches, etc.)', 'value' => '0.010'],
            ['question' => 'I like to find out the "why" of complicated scientific claims.', 'value' => '0.010'],
            ['question' => 'I like to practice artistic painting (watercolor paint, oil paint, etc.).', 'value' => '0.010'],
            ['question' => 'Typing.', 'value' => '0.010'],
            ['question' => 'I would spend hours in a library studying literature, philosophy or history.', 'value' => '0.010'],
            ['question' => 'I enjoy teaching something (to who did not understand the explanation of the class, etc).', 'value' => '0.010'],
            ['question' => 'Studies on drawings and perspectives.', 'value' => '0.010'],
            ['question' => 'When a partner has suffered an accident (injury, etc.), although I am impressed, I tend to help him/her with cold blood.', 'value' => '0.010'],
            ['question' => 'I have artistic "feeling" when I sing or play a musical instrument. Friends often invite me to it.', 'value' => '0.010'],
            ['question' => 'I like to meditate personally on philosophical issues.', 'value' => '0.010'],
            ['question' => 'Studies on modeling or artistic size.', 'value' => '0.010'],
            ['question' => 'On vacation or when I go on an excursion, I am interested in different crops or field problems (use of the land, irrigation system, crops, tree grafts, etc.)', 'value' => '0.010'],
            ['question' => 'Studies on modeling or artistic size.', 'value' => '0.010'],
            ['question' => 'I love music. I wouldn\'t miss a concert.', 'value' => '0.010'],
            ['question' => 'Courses on techniques and improvement of office work.', 'value' => '0.010'],
            ['question' => 'I like to expose and clarify things, speaking in public in a logical and reasoned way.', 'value' => '0.010'],
            ['question' => 'I have skills to make artistic objects (clay modeling, wood carving, etc.)', 'value' => '0.010'],
            ['question' => 'Theatrical art theory (drama, comedy, etc.)', 'value' => '0.010'],
            ['question' => 'I like regular and methodical jobs (one part every day, with a plan and without haste).', 'value' => '0.010'],
            ['question' => 'With interest, I read what I can about authors and music schools.', 'value' => '0.010'],
            ['question' => 'I am rather conciliatory and kind; I like neither to dispute nor to collide with other people’s opinions.', 'value' => '0.010'],
            ['question' => 'When I read novels or stories, it is as if I were seeing places and people, I imagine everything vividly.', 'value' => '0.010'],
            ['question' => 'Almost without pretending, I realize many details. I am an effortless observer.', 'value' => '0.010'],
            ['question' => 'I like to receive precise orders and instructions, even if they are similar, without many words.', 'value' => '0.010'],
            ['question' => 'I like to have an artistically arranged room (paintings, tasteful decoration, etc.)', 'value' => '0.010'],
            ['question' => 'I would like to continue studying after obtaining my degree because I like to keep up with the new advances in science, even if it means self-denial and sacrifice.', 'value' => '0.000'],
            ['question' => 'I would not mind an activity in which I have to travel to places far from where I live (fields, farms, etc.)', 'value' => '0.000'],
            ['question' => 'I would not mind a severe, straight lifestyle.', 'value' => '0.000'],

        ];

        foreach ($questions as $question) {
            Dvi::create($question); ///reformular modelo
        }

        $this->call([
            DviValueQuestionsSeeder::class,
        ]);
    }
}
